FROM aakahlow/scone-npb:latest
MAINTAINER Ayaz Akram <yazakram@ucdavis.edu>

#add benchmarks

ADD gapbs /home/gapbs
ADD sgx-musl.conf /etc/sgx-musl.conf

WORKDIR /home/gapbs

#compile benchmarks
RUN bash -c "make"
